### ISSUE TITLE
VimwikiRebuildTags should skip code blocks with nested syntaxes

### ISSUE THREAD

**Issue by cpkio** [vimwiki/vimwiki#1034]
The test file content is:
```
Tags test file.

{{{rst
   .. role:: raw-role(raw)
      :format: openxml
}}}
```
`:VimwikiRebuildTags` will put the line with `:format:` text into tags file.

`:format:` is an RST directive option and should not be included into tags file. Probably other syntaxes are affected too.

**Comment by brennen** [comment]
@cpkio can you confirm that you're on the `dev` branch for this?  The output of `:VimwikiShowVersion` should be sufficient.

On `dev`, I can't reproduce this, and it looks like the code at least tries to avoid generating tags for things in code blocks.

**Comment by brennen** [comment]
Looks like this *should* have been fixed with #672.

**Comment by cpkio** [comment]
I've pulled `dev`; after rebuilding from scratch I still have a few RST fragments in my `.vimwiki_tags`. When I save the problematic file, the «tag» (`:start-before:` & `:end-after:`) disappears from `.vimwiki_tags`, but if the `.vimwiki_tags` is deleted and tags are built, the «tags» are back.

**Comment by sstallion** [comment]
I just ran into this as well; the issue appears similar to #672. @rane-brown is there a chance a regression was introduced that cased verbatim blocks to be scanned for tags again?

**Comment by tinmarino** [comment]
Closing <= fixed in the dev branch, see the (ugly) tests in [65b9f0e](https://github.com/tinmarino/vimwiki/commit/65b9f0e68b1c4b6c2023a02b22d11a178e13445e)
