### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by Nudin** [vimwiki/vimwiki#504]
The last release of vimwiki was in Mar 2016 (2.3), a lot has changed since than, we don't want users to use this old version nor do we want vimwiki to appear dead. I think we should therefore release a new version soon.
Open question:

- Do we want to wait for some PR/feature/bugfix before releasing a new version or should we just bump the version number and tag a release?
- Which version-number to use? 2.4 or 3.0?
- Should we introduce some release strategy?

**Comment by EinfachToll** [comment]
Yes, I think it's about time. I mainly wanted to include #256 in the next release. It's in the dev branch for a while now and there were a few but not too many bug reports about regressions which it introduced, so I think we can risk a new release.

> Which version-number to use? 2.4 or 3.0?

AFAIR, for the user, nothing earth-shattering has changed, so I would say 2.4

> Should we introduce some release strategy?

The current one is waiting until a non-negligible set of bug fixes and features has piled up and we have the feeling that they didn't introduce any regressions. If you want a more elaborated strategy, feel free to make suggestions.

BTW, here is my personal check list for a release, if you're interested:
- update the changelog in the doc, nicely grouped, with new version number and release date.
- update the list of contributors
- update the version number at the top of the doc file
- if necessary, update the readmy and the home page
- `git checkout master && git merge dev`
- `git tag v2.4`
- `git push --tags`
- in github, go to Releases -> Draft a new release -> choose tag, convert the changlog from the doc to markdown and post it there. Make plans to build an automatic converter and immediately forget this plan.

**Comment by EinfachToll** [comment]
#510 should be fixed before a release.

**Comment by thecliguy** [comment]
@EinfachToll @Nudin Since #510 is closed is there anything else preventing a new release now?

**Comment by hq6** [comment]
@EinfachToll , Is  #256 done?

**Comment by Nudin** [comment]
I propose to 'branch' 54d1a997 as new version. That way we have all the changes that have been in `dev` for a while but still let the huge pille of new changes of the last days hang in `dev` for further testing them.
If noone opposes I will prepare the new version later this week and clean up the branches.

**Comment by hq6** [comment]
I think this makes sense, although I am slightly concerned about the number of issues we've still yet to triage. There is the possibility that some of the existing Issues were introduced by commits in the `dev` branch and they become a problem for more people.  There is also the possibility that `dev` fixes many of the outstanding issues, so this release could also be a blessing on that front.

@ranebrown has been looking at more issues, maybe can comment on how many of them are fixed in `dev` vs introduced in `dev`?

**Comment by ranebrown** [comment]
@Nudin I think creating a release is a great idea. It looks like there are two commits that shouldn't be included that are prior to the one you mentioned - 08ec02a7554e9981967f0a4443ea310b7fbdccd8 and 21f5069e48d92af17a0b8b805342e956282e19ac?

I haven't noticed issues that are only present on the `dev` branch. Most of the time it is either only on `master` or on both. I think with the amount of time it has been since the last release and the number of fixes in `dev` we should go ahead with this.

We should also plan on a more regular release schedule. Maybe some planning should go into what the major features should be and a timeframe?

**Comment by Nudin** [comment]
@ranebrown No, 08ec02a and 21f5069 are not ancestors of 54d1a99, they have been merged into `dev` just a couple of days ago, github just shows all the commits landing in dev linearized in chronological order. Quite confusing…

I'd propose a rule of thumb like "release a new version whenever X new bigger features got merged".

**Comment by hq6** [comment]
I think it may be beneficial to have multiple triggers for releasing a new version, so that bugfixes and small feature tweaks can also be released more quickly.

What about releasing a newer version whenever one of the following occurs, with variables that we can adjust over time as we try to balance between stability and progress.
1. X new bigger features got merged
2. W weeks have passed and more than N pull requests have been merged.
3. More than Z issues have been resolved on `dev`.

**Comment by ranebrown** [comment]
Those are all valid points but I don't think we want to overcomplicate this. Maybe for now we should just discuss a new release whenever one of us thinks there is a valid reason to do so?

**Comment by Nudin** [comment]
It's mostly done. I created a new branch `rel-2.4-pre` and prepared the release. Since it's a quite big release and it's my first release I go with more caution than described in the `CONTRIBUTING.md`. Therefore I created a release candidate:
https://github.com/vimwiki/vimwiki/releases/tag/v2.4-rc1

Please help testing it – if no new regressions are found I will:
- [ ] merge it to master
- [ ] tag it as v2.4
- [ ] release the new version
- [ ] post to HN and my personal blog
on the weekend.

**Comment by hq6** [comment]
@ranebrown , I concur with that sentiment. I'm simply offering a small catalog of possible valid reasons, and would be happy to see more as people think of them. :)

**Comment by ranebrown** [comment]
@Nudin I've been using the tag you created and haven't had any issues so far (other than known stuff, some of which has been fixed more recently). Still testing but wanted to give you an update.

**Comment by hq6** [comment]
@Nudin I was on the dev branch for a while before you released the tag and saw no new issues. I am now on the tag and still see no issues so far.

**Comment by Nudin** [comment]
It's done! 2.4 is out. Spread the word!

**Comment by Nudin** [comment]
I put it on HN and reddit:
https://news.ycombinator.com/item?id=19476590
https://www.reddit.com/r/commandline/comments/b4x8q6/vimwiki_release_24_is_finally_out/

**Comment by Nudin** [comment]
To my big shock I only now noticed, that I never pushed to master… I'm very sorry if that caused confusion.
@hq6 @ranebrown since most people clone master they will only now get the new version – so don't be supprised if a more new issues come in the next days.
